In [1]:
import pandas as pd

In [2]:
best_bets = pd.read_csv(r'C:\Users\redye\Desktop\NBACrit\merged_df.csv')

best_bets

In [3]:
best_bets["over_successful"] = best_bets["PTS_comb_actual"] - best_bets["total1_over"]

# Map the values to 1 or 0 based on the conditions
best_bets["over_successful"] = best_bets["over_successful"].apply(lambda x: 1 if x >= 0 else 0)
best_bets

,GAME_DATE_EST,game_id,home_team,away_team,SEASON,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,...,PTS_comb_actual,book_name_under,book_id_under,total1_under,under_odds,point_average_last10,point_against_average_last10,away_point_average_last10,away_point_against_average_last10,over_successful
0,9/30/2017,11700001,1610612744,1610612743,2017,102,0.411,0.833,0.121,17,...,210,Pinnacle Sports,238,222.5,108,116.226415,104.320755,111.176893,110.534142,0
1,9/30/2017,11700002,1610612747,1610612750,2017,99,0.441,0.706,0.167,27,...,207,Bookmaker,93,216.0,-102,104.435540,111.298407,105.205303,105.693687,0
2,11/1/2017,21700111,1610612752,1610612745,2017,97,0.433,0.846,0.308,23,...,216,Pinnacle Sports,238,215.5,-102,99.916667,107.183333,110.787037,104.050926,1
3,11/1/2017,21700107,1610612755,1610612737,2017,119,0.465,0.560,0.371,36,...,228,5Dimes,19,209.0,-105,105.028571,107.771429,101.091912,104.283088,1
4,11/1/2017,21700108,1610612764,1610612756,2017,116,0.446,0.800,0.333,20,...,238,Heritage,169,228.0,-105,109.972222,104.277778,105.366667,115.866667,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1205,5/28/2018,41700317,1610612745,1610612744,2017,92,0.400,0.591,0.159,17,...,193,Heritage,169,209.0,-105,103.250000,102.750000,108.800000,104.200000,0
1206,5/31/2018,41700401,1610612744,1610612739,2017,124,0.511,0.950,0.361,31,...,238,Heritage,169,218.0,-105,108.550000,102.500000,102.100000,100.900000,1
1207,6/3/2018,41700402,1610612744,1610612739,2017,122,0.573,0.619,0.417,28,...,225,Heritage,169,217.0,-105,108.750000,101.900000,101.650000,101.650000,1
1208,6/6/2018,41700403,1610612739,1610612744,2017,102,0.435,0.765,0.290,20,...,212,Heritage,169,216.5,-105,102.300000,103.150000,109.200000,102.450000,0
1209,6/8/2018,41700404,1610612739,1610612744,2017,85,0.345,0.680,0.296,21,...,193,Heritage,169,217.0,-105,102.500000,103.150000,108.850000,102.550000,0

In [4]:
best_bets["under_successful"] = best_bets["total1_under"] - best_bets["PTS_comb_actual"]

# Map the values to 1 or 0 based on the conditions
best_bets["under_successful"] = best_bets["under_successful"].apply(lambda x: 1 if x >= 0 else 0)
best_bets

,GAME_DATE_EST,game_id,home_team,away_team,SEASON,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,...,book_name_under,book_id_under,total1_under,under_odds,point_average_last10,point_against_average_last10,away_point_average_last10,away_point_against_average_last10,over_successful,under_successful
0,9/30/2017,11700001,1610612744,1610612743,2017,102,0.411,0.833,0.121,17,...,Pinnacle Sports,238,222.5,108,116.226415,104.320755,111.176893,110.534142,0,1
1,9/30/2017,11700002,1610612747,1610612750,2017,99,0.441,0.706,0.167,27,...,Bookmaker,93,216.0,-102,104.435540,111.298407,105.205303,105.693687,0,1
2,11/1/2017,21700111,1610612752,1610612745,2017,97,0.433,0.846,0.308,23,...,Pinnacle Sports,238,215.5,-102,99.916667,107.183333,110.787037,104.050926,1,0
3,11/1/2017,21700107,1610612755,1610612737,2017,119,0.465,0.560,0.371,36,...,5Dimes,19,209.0,-105,105.028571,107.771429,101.091912,104.283088,1,0
4,11/1/2017,21700108,1610612764,1610612756,2017,116,0.446,0.800,0.333,20,...,Heritage,169,228.0,-105,109.972222,104.277778,105.366667,115.866667,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1205,5/28/2018,41700317,1610612745,1610612744,2017,92,0.400,0.591,0.159,17,...,Heritage,169,209.0,-105,103.250000,102.750000,108.800000,104.200000,0,1
1206,5/31/2018,41700401,1610612744,1610612739,2017,124,0.511,0.950,0.361,31,...,Heritage,169,218.0,-105,108.550000,102.500000,102.100000,100.900000,1,0
1207,6/3/2018,41700402,1610612744,1610612739,2017,122,0.573,0.619,0.417,28,...,Heritage,169,217.0,-105,108.750000,101.900000,101.650000,101.650000,1,0
1208,6/6/2018,41700403,1610612739,1610612744,2017,102,0.435,0.765,0.290,20,...,Heritage,169,216.5,-105,102.300000,103.150000,109.200000,102.450000,0,1
1209,6/8/2018,41700404,1610612739,1610612744,2017,85,0.345,0.680,0.296,21,...,Heritage,169,217.0,-105,102.500000,103.150000,108.850000,102.550000,0,1

In [6]:
best_bets.to_csv(r'C:\Users\redye\Desktop\NBACrit\merged_df2.csv')

In [7]:
best_bets['under_successful'].sum()

635

In [8]:
best_bets['over_successful'].sum()

604

In [9]:
new_df = best_bets[best_bets["over_successful"] == best_bets["under_successful"]].copy()

In [10]:
new_df

,GAME_DATE_EST,game_id,home_team,away_team,SEASON,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,...,book_name_under,book_id_under,total1_under,under_odds,point_average_last10,point_against_average_last10,away_point_average_last10,away_point_against_average_last10,over_successful,under_successful
33,11/5/2017,21700137,1610612746,1610612748,2017,101,0.391,0.800,0.290,16,...,Pinnacle Sports,238,205.0,-105,106.28,105.36,100.211111,105.277778,1,1
152,11/22/2017,21700254,1610612739,1610612751,2017,119,0.524,0.704,0.412,21,...,Pinnacle Sports,238,228.0,-109,109.75,110.15,111.161111,112.955556,1,1
239,12/4/2017,21700340,1610612754,1610612752,2017,115,0.535,0.800,0.423,28,...,5Dimes,19,212.0,-109,108.20,107.90,101.322222,104.061111,1,1
254,12/6/2017,21700355,1610612753,1610612737,2017,110,0.469,0.667,0.214,17,...,Heritage,169,216.0,-105,106.10,111.95,102.700000,108.600000,1,1
255,12/6/2017,21700359,1610612749,1610612765,2017,104,0.494,0.692,0.364,22,...,5Dimes,19,204.0,-103,102.10,104.35,104.300000,102.600000,1,1
288,12/11/2017,21700391,1610612741,1610612738,2017,108,0.481,0.720,0.414,23,...,5Dimes,19,193.5,-105,96.90,108.35,104.250000,98.200000,1,1
326,12/16/2017,21700436,1610612763,1610612738,2017,93,0.405,0.882,0.412,18,...,Heritage,169,195.0,-105,95.10,102.45,104.550000,101.000000,1,1
419,12/29/2017,21700521,1610612764,1610612745,2017,121,0.534,0.750,0.500,23,...,Pinnacle Sports,238,225.0,-104,102.80,101.70,117.250000,105.450000,1,1
476,1/6/2018,21700583,1610612764,1610612749,2017,103,0.474,0.724,0.381,25,...,Pinnacle Sports,238,213.5,-103,105.55,104.20,109.600000,108.100000,1,1
481,1/6/2018,21700578,1610612746,1610612744,2017,105,0.429,0.800,0.273,19,...,Bovada,999996,226.0,-105,106.40,106.25,112.650000,105.850000,1,1
482,1/6/2018,21700581,1610612754,1610612741,2017,125,0.558,0.778,0.484,24,...,Pinnacle Sports,238,212.0,-101,105.70,106.70,108.550000,109.950000,1,1
614,1/26/2018,21700720,1610612740,1610612745,2017,115,0.537,0.762,0.407,36,...,Bovada,999996,229.0,-115,112.35,109.75,113.300000,110.050000,1,1
618,1/26/2018,21700715,1610612739,1610612754,2017,115,0.561,0.769,0.351,27,...,Heritage,169,223.0,-105,107.75,112.05,103.450000,102.400000,1,1
740,2/12/2018,21700841,1610612765,1610612740,2017,103,0.368,0.750,0.257,18,...,Heritage,169,222.0,-105,103.90,107.05,110.050000,112.350000,1,1
771,2/23/2018,21700873,1610612765,1610612738,2017,98,0.435,0.667,0.303,16,...,Heritage,169,208.5,-105,103.65,106.70,102.000000,102.150000,1,1
772,2/23/2018,21700874,1610612754,1610612737,2017,116,0.475,0.846,0.321,30,...,Bovada,999996,209.0,-105,105.50,103.55,103.300000,108.000000,1,1
787,2/24/2018,21700891,1610612758,1610612747,2017,108,0.447,0.647,0.520,28,...,5Dimes,19,222.5,-105,102.55,108.20,109.150000,107.250000,1,1
788,2/25/2018,21700892,1610612766,1610612765,2017,114,0.477,0.609,0.457,28,...,5Dimes,19,212.0,-105,108.70,106.85,103.800000,107.300000,1,1
797,2/26/2018,21700901,1610612761,1610612765,2017,123,0.525,0.957,0.447,31,...,5Dimes,19,217.0,-105,113.30,105.45,104.050000,107.500000,1,1
839,3/4/2018,21700943,1610612737,1610612756,2017,113,0.457,0.833,0.515,23,...,Heritage,169,225.5,-105,104.75,110.45,102.300000,115.100000,1,1
936,3/17/2018,21701038,1610612752,1610612766,2017,124,0.490,0.778,0.462,24,...,5Dimes,19,225.0,-105,102.10,112.75,110.850000,112.550000,1,1
961,3/21/2018,21701068,1610612748,1610612752,2017,119,0.556,0.737,0.441,31,...,Bovada,999996,217.0,-105,109.55,107.50,102.350000,111.500000,1,1
1001,3/26/2018,21701105,1610612755,1610612743,2017,123,0.505,0.720,0.448,35,...,5Dimes,19,227.0,-102,111.35,104.40,118.550000,113.200000,1,1
1006,3/27/2018,21701109,1610612761,1610612743,2017,114,0.511,0.778,0.382,33,...,BetOnline,1096,224.0,-107,115.20,107.05,117.600000,113.700000,1,1
1052,4/1/2018,21701144,1610612741,1610612764,2017,113,0.524,0.692,0.529,30,...,Pinnacle Sports,238,207.0,-113,101.20,110.80,105.550000,106.200000,1,1
1099,4/8/2018,21701203,1610612756,1610612744,2017,100,0.424,0.750,0.286,24,...,Heritage,169,217.0,-105,102.65,114.70,107.150000,106.950000,1,1
1107,4/9/2018,21701205,1610612751,1610612741,2017,114,0.500,0.933,0.429,32,...,Heritage,169,219.0,-105,109.35,111.55,102.600000,110.800000,1,1
1124,4/11/2018,21701228,1610612746,1610612747,2017,100,0.494,0.429,0.333,27,...,Heritage,169,215.0,-105,109.70,112.15,109.250000,109.100000,1,1
1129,4/14/2018,41700151,1610612744,1610612759,2017,113,0.543,0.682,0.455,32,...,Pinnacle Sports,238,205.0,-100,105.25,107.30,105.150000,102.050000,1,1

In [11]:
columns_to_keep = ["total1_under", "under_odds", "total1_over", "over_odds"]
third_df = new_df[columns_to_keep].copy()
third_df

      total1_under  under_odds  total1_over  over_odds
33           205.0        -105        205.0       -101
152          228.0        -109        227.5       -105
239          212.0        -109        211.5       -102
254          216.0        -105        215.5       -105
255          204.0        -103        204.0       -105
288          193.5        -105        193.0       -105
326          195.0        -105        195.0       -102
419          225.0        -104        223.0       -115
476          213.5        -103        213.0       -102
481          226.0        -105        225.5        100
482          212.0        -101        211.0       -105
614          229.0        -115        228.0       -100
618          223.0        -105        223.0       -101
740          222.0        -105        220.5       -110
771          208.5        -105        208.0       -105
772          209.0        -105        209.0       -103
787          222.5        -105        220.5       -110
788          212.0        -105        212.0       -102
797          217.0        -105        217.0       -102
839          225.5        -105        224.5       -105
936          225.0        -105        224.0       -105
961          217.0        -105        217.0       -103
1001         227.0        -102        227.0       -105
1006         224.0        -107        223.5       -105
1052         207.0        -113        206.0       -105
1099         217.0        -105        216.5       -104
1107         219.0        -105        218.5       -104
1124         215.0        -105        214.0       -110
1129         205.0        -100        205.0       -105