In [23]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf

## Split the Data into Training and Testing Sets

In [25]:
from google.colab import files
uploaded = files.upload()

Saving merged_df2.csv to merged_df2.csv

In [27]:
# Read the CSV file
import io

nba_df = pd.read_csv(io.BytesIO(uploaded['merged_df2.csv']))
nba_df.head()

,Unnamed: 0,GAME_DATE_EST,game_id,home_team,away_team,SEASON,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,...,book_name_under,book_id_under,total1_under,under_odds,point_average_last10,point_against_average_last10,away_point_average_last10,away_point_against_average_last10,over_successful,under_successful
0,0,9/30/2017,11700001,1610612744,1610612743,2017,102,0.411,0.833,0.121,...,Pinnacle Sports,238,222.5,108,116.226415,104.320755,111.176893,110.534142,0,1
1,1,9/30/2017,11700002,1610612747,1610612750,2017,99,0.441,0.706,0.167,...,Bookmaker,93,216.0,-102,104.435540,111.298407,105.205303,105.693687,0,1
2,2,11/1/2017,21700111,1610612752,1610612745,2017,97,0.433,0.846,0.308,...,Pinnacle Sports,238,215.5,-102,99.916667,107.183333,110.787037,104.050926,1,0
3,3,11/1/2017,21700107,1610612755,1610612737,2017,119,0.465,0.560,0.371,...,5Dimes,19,209.0,-105,105.028571,107.771429,101.091912,104.283088,1,0
4,4,11/1/2017,21700108,1610612764,1610612756,2017,116,0.446,0.800,0.333,...,Heritage,169,228.0,-105,109.972222,104.277778,105.366667,115.866667,1,0

In [28]:
# Review the DataFrame
nba_df.head(10)

,Unnamed: 0,GAME_DATE_EST,game_id,home_team,away_team,SEASON,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,...,book_name_under,book_id_under,total1_under,under_odds,point_average_last10,point_against_average_last10,away_point_average_last10,away_point_against_average_last10,over_successful,under_successful
0,0,9/30/2017,11700001,1610612744,1610612743,2017,102,0.411,0.833,0.121,...,Pinnacle Sports,238,222.5,108,116.226415,104.320755,111.176893,110.534142,0,1
1,1,9/30/2017,11700002,1610612747,1610612750,2017,99,0.441,0.706,0.167,...,Bookmaker,93,216.0,-102,104.435540,111.298407,105.205303,105.693687,0,1
2,2,11/1/2017,21700111,1610612752,1610612745,2017,97,0.433,0.846,0.308,...,Pinnacle Sports,238,215.5,-102,99.916667,107.183333,110.787037,104.050926,1,0
3,3,11/1/2017,21700107,1610612755,1610612737,2017,119,0.465,0.560,0.371,...,5Dimes,19,209.0,-105,105.028571,107.771429,101.091912,104.283088,1,0
4,4,11/1/2017,21700108,1610612764,1610612756,2017,116,0.446,0.800,0.333,...,Heritage,169,228.0,-105,109.972222,104.277778,105.366667,115.866667,1,0
5,5,11/1/2017,21700110,1610612748,1610612741,2017,97,0.410,0.895,0.387,...,Pinnacle Sports,238,196.5,-105,102.906250,104.125000,96.233333,106.366667,0,1
6,6,11/1/2017,21700115,1610612762,1610612757,2017,112,0.378,0.861,0.448,...,5Dimes,19,192.0,-105,100.800000,95.400000,109.583333,99.666667,1,0
7,7,11/1/2017,21700109,1610612738,1610612758,2017,113,0.488,0.842,0.415,...,Bovada,999996,196.0,-110,103.416667,94.816667,93.112500,102.887500,1,0
8,8,11/1/2017,21700113,1610612740,1610612750,2017,98,0.429,0.857,0.258,...,Pinnacle Sports,238,225.0,-105,105.172619,108.437500,108.260417,106.833333,0,1
9,9,11/1/2017,21700114,1610612743,1610612761,2017,129,0.534,0.655,0.500,...,Pinnacle Sports,238,217.5,-105,110.292271,108.974638,106.501374,101.627747,1,0

In [ ]:
# Rename columns
#nba_df.rename(columns = {'point_againts_average_last10':'point_against_average_last10', 'away_point_againts_average_last10':'away_point_against_average_last10'}, inplace = True)

In [ ]:
# Drop non-beneficial columns if applicable
# nba_df.drop(columns=[''], inplace=True)

In [29]:
# Determine the number of unique values in each column.
nba_df.nunique()

Unnamed: 0                           1210
GAME_DATE_EST                         198
game_id                              1210
home_team                              30
away_team                              30
SEASON                                  1
PTS_home                               68
FG_PCT_home                           223
FT_PCT_home                           174
FG3_PCT_home                          219
AST_home                               29
REB_home                               37
PTS_away                               68
FG_PCT_away                           225
FT_PCT_away                           181
FG3_PCT_away                          207
AST_away                               33
REB_away                               42
HOME_TEAM_WINS                          2
book_name_over                          9
book_id_over                            9
total1_over                            92
over_odds                              21
PTS_comb_actual                       106
book_name_under                         8
book_id_under                           8
total1_under                           89
under_odds                             22
point_average_last10                  491
point_against_average_last10          481
away_point_average_last10             495
away_point_against_average_last10     484
over_successful                         2
under_successful                        2
dtype: int64

In [30]:
# Look at actual game points value counts for binning
nba_df['PTS_comb_actual'].value_counts()

215    34
207    33
205    27
213    27
211    27
       ..
255     1
250     1
158     1
171     1
166     1
Name: PTS_comb_actual, Length: 106, dtype: int64

In [31]:
# Choose a cutoff value and create a list of actual game points to be replaced
# use the variable name `pts_types_to_replace`
pts_types = pd.DataFrame(nba_df['PTS_comb_actual'].value_counts()).reset_index()

pts_types_to_replace = []

for index, row in pts_types.iterrows():
    if row['PTS_comb_actual'] < 10:
        pts_types_to_replace.append(row['index'])
pts_types_to_replace


# Replace in dataframe
for pts_types in pts_types_to_replace:
    nba_df['PTS_comb_actual'] = nba_df['PTS_comb_actual'].replace(pts_types,"Other")

# Check to make sure binning was successful
nba_df['PTS_comb_actual'].value_counts()

Other    189
215       34
207       33
213       27
206       27
205       27
211       27
217       26
192       25
208       25
209       25
223       25
204       24
202       24
218       24
221       24
224       23
201       23
226       23
227       22
225       21
193       21
210       21
233       20
187       20
220       19
212       19
203       19
200       19
214       18
195       17
197       17
231       17
191       16
190       16
196       16
232       15
219       15
234       15
198       14
189       14
228       14
216       14
237       14
241       13
194       13
240       13
229       13
199       13
188       13
230       11
236       11
235       11
242       11
Name: PTS_comb_actual, dtype: int64

In [32]:
# Look at point-average-last10 value counts for binning
# Try other columns
pa_counts = nba_df['over_odds'].value_counts()
pa_counts

-105    655
-103    108
-102     77
-104     63
-100     59
-110     57
-101     35
-115     25
 102     21
-107     19
 100     16
-108     15
-106     15
-109     14
 101      8
 104      6
 105      5
 103      4
 109      3
-113      2
 108      2
-111      1
Name: under_odds, dtype: int64

In [42]:
# Choose a cutoff value and create a list of YYYY to be replaced
# use the variable name `yyyy_to_replace`
oo_types = pd.DataFrame(nba_df['over_odds'].value_counts()).reset_index()

oo_to_replace = []

for index, row in oo_types.iterrows():
    if row['over_odds'] < 5:
        oo_to_replace.append(row['index'])
oo_to_replace

# Replace in dataframe
for oo_types in oo_to_replace:
    nba_df['over_odds'] = nba_df['over_odds'].replace(oo_types,"Other")

# Check to make sure binning was successful
nba_df['over_odds'].value_counts()

-105     555
-103     138
-102     116
-110      66
-104      55
-101      48
-107      43
-108      37
-100      37
100       26
102       22
-106      13
-115      13
101       12
-109       8
103        8
Other      7
104        6
Name: over_odds, dtype: int64

In [43]:
# Convert categorical data to numeric with `pd.get_dummies`
nba_df = pd.get_dummies(nba_df)

In [44]:
# Split our preprocessed data into our features and target arrays
y = nba_df['over_successful']
X = nba_df.drop(columns=['over_successful'])

In [45]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 1)

In [46]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [47]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
from tensorflow import keras
from tensorflow.keras import layers
num_input_features = len(X_train_scaled[0])

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(layers.Dense(units = 100, activation = 'relu', input_dim = num_input_features))

# Second hidden layer
nn.add(layers.Dense(units = 50, activation = 'elu'))

# Output layer
nn.add(layers.Dense(units = 1, activation = 'sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 100)               33300

 dense_4 (Dense)             (None, 50)                5050

 dense_5 (Dense)             (None, 1)                 51

=================================================================
Total params: 38,401
Trainable params: 38,401
Non-trainable params: 0
_________________________________________________________________

In [48]:
# Compile the model
nn.compile(loss ='binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [49]:
# Train the model
fit_modelnn = nn.fit(X_train_scaled, y_train, epochs = 100)

Epoch 1/100
29/29 [==============================] - 1s 3ms/step - loss: 0.6157 - accuracy: 0.6714
Epoch 2/100
29/29 [==============================] - 0s 3ms/step - loss: 0.2530 - accuracy: 0.9327
Epoch 3/100
29/29 [==============================] - 0s 3ms/step - loss: 0.1115 - accuracy: 0.9757
Epoch 4/100
29/29 [==============================] - 0s 3ms/step - loss: 0.0507 - accuracy: 0.9945
Epoch 5/100
29/29 [==============================] - 0s 3ms/step - loss: 0.0260 - accuracy: 0.9989
Epoch 6/100
29/29 [==============================] - 0s 3ms/step - loss: 0.0155 - accuracy: 1.0000
Epoch 7/100
29/29 [==============================] - 0s 3ms/step - loss: 0.0102 - accuracy: 1.0000
Epoch 8/100
29/29 [==============================] - 0s 3ms/step - loss: 0.0074 - accuracy: 1.0000
Epoch 9/100
29/29 [==============================] - 0s 3ms/step - loss: 0.0050 - accuracy: 1.0000
Epoch 10/100
29/29 [==============================] - 0s 3ms/step - loss: 0.0039 - accuracy: 1.0000
Epoch 11/100
29/29 [==============================] - 0s 3ms/step - loss: 0.0030 - accuracy: 1.0000
Epoch 12/100
29/29 [==============================] - 0s 4ms/step - loss: 0.0025 - accuracy: 1.0000
Epoch 13/100
29/29 [==============================] - 0s 3ms/step - loss: 0.0021 - accuracy: 1.0000
Epoch 14/100
29/29 [==============================] - 0s 3ms/step - loss: 0.0017 - accuracy: 1.0000
Epoch 15/100
29/29 [==============================] - 0s 3ms/step - loss: 0.0015 - accuracy: 1.0000
Epoch 16/100
29/29 [==============================] - 0s 3ms/step - loss: 0.0013 - accuracy: 1.0000
Epoch 17/100
29/29 [==============================] - 0s 3ms/step - loss: 0.0011 - accuracy: 1.0000
Epoch 18/100
29/29 [==============================] - 0s 3ms/step - loss: 9.8300e-04 - accuracy: 1.0000
Epoch 19/100
29/29 [==============================] - 0s 3ms/step - loss: 8.7758e-04 - accuracy: 1.0000
Epoch 20/100
29/29 [==============================] - 0s 3ms/step - loss: 7.8244e-04 - accuracy: 1.0000
Epoch 21/100
29/29 [==============================] - 0s 3ms/step - loss: 7.0078e-04 - accuracy: 1.0000
Epoch 22/100
29/29 [==============================] - 0s 3ms/step - loss: 6.3635e-04 - accuracy: 1.0000
Epoch 23/100
29/29 [==============================] - 0s 3ms/step - loss: 5.7595e-04 - accuracy: 1.0000
Epoch 24/100
29/29 [==============================] - 0s 3ms/step - loss: 5.2866e-04 - accuracy: 1.0000
Epoch 25/100
29/29 [==============================] - 0s 3ms/step - loss: 4.8253e-04 - accuracy: 1.0000
Epoch 26/100
29/29 [==============================] - 0s 3ms/step - loss: 4.4190e-04 - accuracy: 1.0000
Epoch 27/100
29/29 [==============================] - 0s 3ms/step - loss: 4.0842e-04 - accuracy: 1.0000
Epoch 28/100
29/29 [==============================] - 0s 3ms/step - loss: 3.7970e-04 - accuracy: 1.0000
Epoch 29/100
29/29 [==============================] - 0s 3ms/step - loss: 3.5163e-04 - accuracy: 1.0000
Epoch 30/100
29/29 [==============================] - 0s 3ms/step - loss: 3.2472e-04 - accuracy: 1.0000
Epoch 31/100
29/29 [==============================] - 0s 3ms/step - loss: 3.0326e-04 - accuracy: 1.0000
Epoch 32/100
29/29 [==============================] - 0s 3ms/step - loss: 2.8355e-04 - accuracy: 1.0000
Epoch 33/100
29/29 [==============================] - 0s 3ms/step - loss: 2.6548e-04 - accuracy: 1.0000
Epoch 34/100
29/29 [==============================] - 0s 3ms/step - loss: 2.4739e-04 - accuracy: 1.0000
Epoch 35/100
29/29 [==============================] - 0s 3ms/step - loss: 2.3437e-04 - accuracy: 1.0000
Epoch 36/100
29/29 [==============================] - 0s 3ms/step - loss: 2.1881e-04 - accuracy: 1.0000
Epoch 37/100
29/29 [==============================] - 0s 3ms/step - loss: 2.0664e-04 - accuracy: 1.0000
Epoch 38/100
29/29 [==============================] - 0s 3ms/step - loss: 1.9439e-04 - accuracy: 1.0000
Epoch 39/100
29/29 [==============================] - 0s 3ms/step - loss: 1.8515e-04 - accuracy: 1.0000
Epoch 40/100
29/29 [==============================] - 0s 3ms/step - loss: 1.7441e-04 - accuracy: 1.0000
Epoch 41/100
29/29 [==============================] - 0s 4ms/step - loss: 1.6565e-04 - accuracy: 1.0000
Epoch 42/100
29/29 [==============================] - 0s 3ms/step - loss: 1.5679e-04 - accuracy: 1.0000
Epoch 43/100
29/29 [==============================] - 0s 3ms/step - loss: 1.4880e-04 - accuracy: 1.0000
Epoch 44/100
29/29 [==============================] - 0s 3ms/step - loss: 1.4197e-04 - accuracy: 1.0000
Epoch 45/100
29/29 [==============================] - 0s 3ms/step - loss: 1.3424e-04 - accuracy: 1.0000
Epoch 46/100
29/29 [==============================] - 0s 3ms/step - loss: 1.2837e-04 - accuracy: 1.0000
Epoch 47/100
29/29 [==============================] - 0s 3ms/step - loss: 1.2179e-04 - accuracy: 1.0000
Epoch 48/100
29/29 [==============================] - 0s 3ms/step - loss: 1.1675e-04 - accuracy: 1.0000
Epoch 49/100
29/29 [==============================] - 0s 3ms/step - loss: 1.1143e-04 - accuracy: 1.0000
Epoch 50/100
29/29 [==============================] - 0s 3ms/step - loss: 1.0681e-04 - accuracy: 1.0000
Epoch 51/100
29/29 [==============================] - 0s 3ms/step - loss: 1.0183e-04 - accuracy: 1.0000
Epoch 52/100
29/29 [==============================] - 0s 3ms/step - loss: 9.7812e-05 - accuracy: 1.0000
Epoch 53/100
29/29 [==============================] - 0s 3ms/step - loss: 9.3600e-05 - accuracy: 1.0000
Epoch 54/100
29/29 [==============================] - 0s 3ms/step - loss: 8.9668e-05 - accuracy: 1.0000
Epoch 55/100
29/29 [==============================] - 0s 4ms/step - loss: 8.6113e-05 - accuracy: 1.0000
Epoch 56/100
29/29 [==============================] - 0s 3ms/step - loss: 8.3127e-05 - accuracy: 1.0000
Epoch 57/100
29/29 [==============================] - 0s 3ms/step - loss: 7.9642e-05 - accuracy: 1.0000
Epoch 58/100
29/29 [==============================] - 0s 3ms/step - loss: 7.7312e-05 - accuracy: 1.0000
Epoch 59/100
29/29 [==============================] - 0s 3ms/step - loss: 7.3517e-05 - accuracy: 1.0000
Epoch 60/100
29/29 [==============================] - 0s 3ms/step - loss: 7.0755e-05 - accuracy: 1.0000
Epoch 61/100
29/29 [==============================] - 0s 3ms/step - loss: 6.7894e-05 - accuracy: 1.0000
Epoch 62/100
29/29 [==============================] - 0s 3ms/step - loss: 6.5471e-05 - accuracy: 1.0000
Epoch 63/100
29/29 [==============================] - 0s 3ms/step - loss: 6.3203e-05 - accuracy: 1.0000
Epoch 64/100
29/29 [==============================] - 0s 3ms/step - loss: 6.1113e-05 - accuracy: 1.0000
Epoch 65/100
29/29 [==============================] - 0s 4ms/step - loss: 5.8790e-05 - accuracy: 1.0000
Epoch 66/100
29/29 [==============================] - 0s 3ms/step - loss: 5.7100e-05 - accuracy: 1.0000
Epoch 67/100
29/29 [==============================] - 0s 3ms/step - loss: 5.4917e-05 - accuracy: 1.0000
Epoch 68/100
29/29 [==============================] - 0s 3ms/step - loss: 5.3103e-05 - accuracy: 1.0000
Epoch 69/100
29/29 [==============================] - 0s 3ms/step - loss: 5.1417e-05 - accuracy: 1.0000
Epoch 70/100
29/29 [==============================] - 0s 3ms/step - loss: 4.9693e-05 - accuracy: 1.0000
Epoch 71/100
29/29 [==============================] - 0s 3ms/step - loss: 4.8000e-05 - accuracy: 1.0000
Epoch 72/100
29/29 [==============================] - 0s 3ms/step - loss: 4.6560e-05 - accuracy: 1.0000
Epoch 73/100
29/29 [==============================] - 0s 3ms/step - loss: 4.5094e-05 - accuracy: 1.0000
Epoch 74/100
29/29 [==============================] - 0s 5ms/step - loss: 4.3573e-05 - accuracy: 1.0000
Epoch 75/100
29/29 [==============================] - 0s 4ms/step - loss: 4.2179e-05 - accuracy: 1.0000
Epoch 76/100
29/29 [==============================] - 0s 5ms/step - loss: 4.0964e-05 - accuracy: 1.0000
Epoch 77/100
29/29 [==============================] - 0s 4ms/step - loss: 3.9737e-05 - accuracy: 1.0000
Epoch 78/100
29/29 [==============================] - 0s 5ms/step - loss: 3.8572e-05 - accuracy: 1.0000
Epoch 79/100
29/29 [==============================] - 0s 4ms/step - loss: 3.7230e-05 - accuracy: 1.0000
Epoch 80/100
29/29 [==============================] - 0s 4ms/step - loss: 3.6189e-05 - accuracy: 1.0000
Epoch 81/100
29/29 [==============================] - 0s 4ms/step - loss: 3.5053e-05 - accuracy: 1.0000
Epoch 82/100
29/29 [==============================] - 0s 4ms/step - loss: 3.4102e-05 - accuracy: 1.0000
Epoch 83/100
29/29 [==============================] - 0s 5ms/step - loss: 3.3155e-05 - accuracy: 1.0000
Epoch 84/100
29/29 [==============================] - 0s 4ms/step - loss: 3.2189e-05 - accuracy: 1.0000
Epoch 85/100
29/29 [==============================] - 0s 4ms/step - loss: 3.1246e-05 - accuracy: 1.0000
Epoch 86/100
29/29 [==============================] - 0s 4ms/step - loss: 3.0393e-05 - accuracy: 1.0000
Epoch 87/100
29/29 [==============================] - 0s 4ms/step - loss: 2.9619e-05 - accuracy: 1.0000
Epoch 88/100
29/29 [==============================] - 0s 4ms/step - loss: 2.8657e-05 - accuracy: 1.0000
Epoch 89/100
29/29 [==============================] - 0s 4ms/step - loss: 2.7903e-05 - accuracy: 1.0000
Epoch 90/100
29/29 [==============================] - 0s 5ms/step - loss: 2.7157e-05 - accuracy: 1.0000
Epoch 91/100
29/29 [==============================] - 0s 4ms/step - loss: 2.6410e-05 - accuracy: 1.0000
Epoch 92/100
29/29 [==============================] - 0s 4ms/step - loss: 2.5653e-05 - accuracy: 1.0000
Epoch 93/100
29/29 [==============================] - 0s 4ms/step - loss: 2.4953e-05 - accuracy: 1.0000
Epoch 94/100
29/29 [==============================] - 0s 4ms/step - loss: 2.4365e-05 - accuracy: 1.0000
Epoch 95/100
29/29 [==============================] - 0s 4ms/step - loss: 2.3666e-05 - accuracy: 1.0000
Epoch 96/100
29/29 [==============================] - 0s 4ms/step - loss: 2.3065e-05 - accuracy: 1.0000
Epoch 97/100
29/29 [==============================] - 0s 4ms/step - loss: 2.2474e-05 - accuracy: 1.0000
Epoch 98/100
29/29 [==============================] - 0s 4ms/step - loss: 2.1861e-05 - accuracy: 1.0000
Epoch 99/100
29/29 [==============================] - 0s 4ms/step - loss: 2.1333e-05 - accuracy: 1.0000
Epoch 100/100
29/29 [==============================] - 0s 5ms/step - loss: 2.0771e-05 - accuracy: 1.0000

In [50]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

10/10 - 0s - loss: 0.3985 - accuracy: 0.9043 - 186ms/epoch - 19ms/step
Loss: 0.39850521087646484, Accuracy: 0.9042904376983643