In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving merged_df3.5.csv to merged_df3.5.csv

In [ ]:
# Read the CSV file
import io
nba_df = pd.read_csv(io.BytesIO(uploaded['merged_df3.5.csv']))

nba_df.head()

,game_date_est,game_id,home_team,away_team,home_team_wins,pts_home,pts_away,pts_comb_actual,book_name_over,total1_over,over_odds,book_name_under,total1_under,under_odds,over_successful,under_successful
0,9/30/2017,11700001,GSW,DEN,0,102,108,210,Intertops,223.0,-110,Pinnacle Sports,222.5,108,0,1
1,9/30/2017,11700002,LAL,MIN,0,99,108,207,Pinnacle Sports,214.5,-110,Bookmaker,216.0,-102,0,1
2,11/1/2017,21700111,NYK,HOU,0,97,119,216,5Dimes,214.0,-107,Pinnacle Sports,215.5,-102,1,0
3,11/1/2017,21700107,PHI,ATL,1,119,109,228,Pinnacle Sports,209.0,-104,5Dimes,209.0,-105,1,0
4,11/1/2017,21700108,WAS,PHX,0,116,122,238,Pinnacle Sports,227.5,-105,Heritage,228.0,-105,1,0

In [ ]:
# Drop non-beneficial columns if applicable
nba_df.drop(columns=['total1_over'], inplace=True)
nba_df.drop(columns=['total1_under'], inplace=True)
nba_df.drop(columns=['pts_away'], inplace=True)
nba_df.drop(columns=['pts_home'], inplace=True)
nba_df.drop(columns=['home_team_wins'], inplace=True)
nba_df.drop(columns=['pts_comb_actual'], inplace=True)

nba_df.head()

,game_date_est,game_id,home_team,away_team,book_name_over,over_odds,book_name_under,under_odds,over_successful,under_successful
0,9/30/2017,11700001,GSW,DEN,Intertops,-110,Pinnacle Sports,108,0,1
1,9/30/2017,11700002,LAL,MIN,Pinnacle Sports,-110,Bookmaker,-102,0,1
2,11/1/2017,21700111,NYK,HOU,5Dimes,-107,Pinnacle Sports,-102,1,0
3,11/1/2017,21700107,PHI,ATL,Pinnacle Sports,-104,5Dimes,-105,1,0
4,11/1/2017,21700108,WAS,PHX,Pinnacle Sports,-105,Heritage,-105,1,0

In [ ]:
# Determine the number of unique values in each column.
nba_df.nunique()

game_date_est        198
game_id             1210
home_team             30
away_team             30
book_name_over         9
over_odds             21
book_name_under        8
under_odds            22
over_successful        2
under_successful       2
dtype: int64

In [ ]:
# Look at over_odds value counts
over_counts = nba_df['over_odds'].value_counts()
over_counts

-105    555
-103    138
-102    116
-110     66
-104     55
-101     48
-107     43
-108     37
-100     37
 100     26
 102     22
-115     13
-106     13
 101     12
-109      8
 103      8
 104      6
 105      4
-111      1
 106      1
 109      1
Name: over_odds, dtype: int64

In [ ]:
# Look at under_odds value counts
under_counts = nba_df['under_odds'].value_counts()
under_counts

-105    655
-103    108
-102     77
-104     63
-100     59
-110     57
-101     35
-115     25
 102     21
-107     19
 100     16
-108     15
-106     15
-109     14
 101      8
 104      6
 105      5
 103      4
 109      3
-113      2
 108      2
-111      1
Name: under_odds, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
nba_numeric = pd.get_dummies(nba_df)
nba_numeric.head()

,game_id,over_odds,under_odds,over_successful,under_successful,game_date_est_1/1/2018,game_date_est_1/10/2018,game_date_est_1/11/2018,game_date_est_1/12/2018,game_date_est_1/13/2018,...,book_name_over_Pinnacle Sports,book_name_over_YouWager,book_name_under_5Dimes,book_name_under_BetOnline,book_name_under_Bookmaker,book_name_under_Bovada,book_name_under_Heritage,book_name_under_Intertops,book_name_under_Pinnacle Sports,book_name_under_YouWager
0,11700001,-110,108,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,11700002,-110,-102,0,1,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
2,21700111,-107,-102,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,21700107,-104,-105,1,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,0
4,21700108,-105,-105,1,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0

In [ ]:
# Split our preprocessed data into our features and target arrays
X = nba_numeric.drop(['over_successful'], axis=1)
y = nba_numeric['under_successful']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=58)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 10
hidden_nodes_layer2 = 8
hidden_nodes_layer3= 6

nba_model = tf.keras.models.Sequential()

# First hidden layer
nba_model.add(tf.keras.layers.Dense(units=hidden_nodes_layer1,
             input_dim=number_input_features, activation="relu"))

# Second hidden layer
nba_model.add(tf.keras.layers.Dense(
    units=hidden_nodes_layer2, activation="relu"))

# Third hidden layer
nba_model.add(tf.keras.layers.Dense(
    units=hidden_nodes_layer3, activation="relu"))

# Output layer
nba_model.add(tf.keras.layers.Dense(units=1, activation="relu"))


# Check the structure of the model
nba_model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_2 (Dense)             (None, 10)                2800

 dense_3 (Dense)             (None, 8)                 88

 dense_4 (Dense)             (None, 6)                 54

 dense_5 (Dense)             (None, 1)                 7

=================================================================
Total params: 2,949
Trainable params: 2,949
Non-trainable params: 0
_________________________________________________________________

In [ ]:
# Compile the model
nba_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# Train the model
fit_model = nba_model.fit(X_train_scaled, y_train, epochs=200)

In [ ]:
# Evaluate the model
model_loss, model_accuracy = nba_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

10/10 - 0s - loss: 7.9925 - accuracy: 0.4818 - 196ms/epoch - 20ms/step
Loss: 7.992464542388916, Accuracy: 0.48184818029403687