In [1]:
import pandas as pd

In [2]:
best_bets = pd.read_csv(r'C:\Users\redye\Desktop\NBACrit\merged_df.csv')

best_bets

In [3]:
best_bets["over_successful"] = best_bets["PTS_comb_actual"] - best_bets["total1_over"]

# Map the values to 1 or 0 based on the conditions
best_bets["over_successful"] = best_bets["over_successful"].apply(lambda x: 1 if x >= 0 else 0)
best_bets

,GAME_DATE_EST,game_id,home_team,away_team,SEASON,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,...,PTS_comb_actual,book_name_under,book_id_under,total1_under,under_odds,point_average_last10,point_against_average_last10,away_point_average_last10,away_point_against_average_last10,over_successful
0,9/30/2017,11700001,1610612744,1610612743,2017,102,0.411,0.833,0.121,17,...,210,Pinnacle Sports,238,222.5,108,116.226415,104.320755,111.176893,110.534142,0
1,9/30/2017,11700002,1610612747,1610612750,2017,99,0.441,0.706,0.167,27,...,207,Bookmaker,93,216.0,-102,104.435540,111.298407,105.205303,105.693687,0
2,11/1/2017,21700111,1610612752,1610612745,2017,97,0.433,0.846,0.308,23,...,216,Pinnacle Sports,238,215.5,-102,99.916667,107.183333,110.787037,104.050926,1
3,11/1/2017,21700107,1610612755,1610612737,2017,119,0.465,0.560,0.371,36,...,228,5Dimes,19,209.0,-105,105.028571,107.771429,101.091912,104.283088,1
4,11/1/2017,21700108,1610612764,1610612756,2017,116,0.446,0.800,0.333,20,...,238,Heritage,169,228.0,-105,109.972222,104.277778,105.366667,115.866667,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1205,5/28/2018,41700317,1610612745,1610612744,2017,92,0.400,0.591,0.159,17,...,193,Heritage,169,209.0,-105,103.250000,102.750000,108.800000,104.200000,0
1206,5/31/2018,41700401,1610612744,1610612739,2017,124,0.511,0.950,0.361,31,...,238,Heritage,169,218.0,-105,108.550000,102.500000,102.100000,100.900000,1
1207,6/3/2018,41700402,1610612744,1610612739,2017,122,0.573,0.619,0.417,28,...,225,Heritage,169,217.0,-105,108.750000,101.900000,101.650000,101.650000,1
1208,6/6/2018,41700403,1610612739,1610612744,2017,102,0.435,0.765,0.290,20,...,212,Heritage,169,216.5,-105,102.300000,103.150000,109.200000,102.450000,0
1209,6/8/2018,41700404,1610612739,1610612744,2017,85,0.345,0.680,0.296,21,...,193,Heritage,169,217.0,-105,102.500000,103.150000,108.850000,102.550000,0

In [4]:
best_bets["under_successful"] = best_bets["total1_under"] - best_bets["PTS_comb_actual"]

# Map the values to 1 or 0 based on the conditions
best_bets["under_successful"] = best_bets["under_successful"].apply(lambda x: 1 if x >= 0 else 0)
best_bets

,GAME_DATE_EST,game_id,home_team,away_team,SEASON,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,...,book_name_under,book_id_under,total1_under,under_odds,point_average_last10,point_against_average_last10,away_point_average_last10,away_point_against_average_last10,over_successful,under_successful
0,9/30/2017,11700001,1610612744,1610612743,2017,102,0.411,0.833,0.121,17,...,Pinnacle Sports,238,222.5,108,116.226415,104.320755,111.176893,110.534142,0,1
1,9/30/2017,11700002,1610612747,1610612750,2017,99,0.441,0.706,0.167,27,...,Bookmaker,93,216.0,-102,104.435540,111.298407,105.205303,105.693687,0,1
2,11/1/2017,21700111,1610612752,1610612745,2017,97,0.433,0.846,0.308,23,...,Pinnacle Sports,238,215.5,-102,99.916667,107.183333,110.787037,104.050926,1,0
3,11/1/2017,21700107,1610612755,1610612737,2017,119,0.465,0.560,0.371,36,...,5Dimes,19,209.0,-105,105.028571,107.771429,101.091912,104.283088,1,0
4,11/1/2017,21700108,1610612764,1610612756,2017,116,0.446,0.800,0.333,20,...,Heritage,169,228.0,-105,109.972222,104.277778,105.366667,115.866667,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1205,5/28/2018,41700317,1610612745,1610612744,2017,92,0.400,0.591,0.159,17,...,Heritage,169,209.0,-105,103.250000,102.750000,108.800000,104.200000,0,1
1206,5/31/2018,41700401,1610612744,1610612739,2017,124,0.511,0.950,0.361,31,...,Heritage,169,218.0,-105,108.550000,102.500000,102.100000,100.900000,1,0
1207,6/3/2018,41700402,1610612744,1610612739,2017,122,0.573,0.619,0.417,28,...,Heritage,169,217.0,-105,108.750000,101.900000,101.650000,101.650000,1,0
1208,6/6/2018,41700403,1610612739,1610612744,2017,102,0.435,0.765,0.290,20,...,Heritage,169,216.5,-105,102.300000,103.150000,109.200000,102.450000,0,1
1209,6/8/2018,41700404,1610612739,1610612744,2017,85,0.345,0.680,0.296,21,...,Heritage,169,217.0,-105,102.500000,103.150000,108.850000,102.550000,0,1

In [6]:
best_bets.to_csv(r'C:\Users\redye\Desktop\NBACrit\merged_df2.csv')